blueprint:
  name: "Danfoss Radiator Covered"
  description: "# Danfoss Ally - Radiator Covered


    The temperature sensor of the TRV is — due to its design — relatively close to the heat source (i.e. the hot water in the radiator).
    Thus there are situations where the `local_temperature` measured by the TRV is not accurate enough:

    - If the radiator is covered behind curtains or furniture, if the room is rather big, or if the radiator itself is big and the flow
    emperature is high, then the temperature in the room may easily diverge from the `local_temperature` measured by the TRV by 5°C to 8°C.

    - In this case you might choose to use an external room sensor and send the measured value of the external room sensor to
    the `External_measured_room_sensor` property. The way the TRV operates on the `External_measured_room_sensor` depends on the setting
    of the `Radiator_covered` property:


    ### If `Radiator_covered` is `false` (Auto Offset Mode):

    You *must* set the `External_measured_room_sensor` property *at least* every 3 hours.
    After 3 hours the TRV disables this function and resets the value of the `External_measured_room_sensor` property to -8000 (disabled).

    You *should* set the `External_measured_room_sensor` property *at most* every 30 minutes or every 0.1K change in measured room temperature.


    ### If `Radiator_covered` is `true` (Room Sensor Mode):

    You *must* set the `External_measured_room_sensor` property *at least* every 30 minutes.
    After 35 minutes the TRV disables this function and resets the value of the `External_measured_room_sensor` property to -8000 (disabled).

    You *should* set the `External_measured_room_sensor` property *at most* every 5 minutes or every 0.1K change in measured room temperature.
    "
  domain: automation

  input:
    mode:
      name: Radiator Covered Mode
      description: "This defines the time pattern trigger for the automation.

        *Room Sensor Mode*: every 5 minutes.

        *Auto Offset Mode*: every 30 minutes.
        "
      default: "true"
      selector:
        select:
          options:
            - label: Room Sensor Mode
              value: "true"
            - label: Auto Offset Mode
              value: "false"

    climate:
      name: External Measured Room Sensor
      description: "Select the entity 'external_measured_room_sensor' of all target Danfoss TRVs"
      selector:
        entity:
          integration: mqtt
          domain: number
          multiple: true

    external_measured_room_sensor:
      name: Room Sensor
      description: The external room temperature sensor
      selector:
        entity:
          device_class: temperature

mode: single

variables:
  external_measured_room_sensor: !input "external_measured_room_sensor"

trigger:
  - platform: time_pattern
    minutes: "/5"
  - platform: state
    entity_id:
      - !input "external_measured_room_sensor"

condition: []
action:
  service: number.set_value
  data:
    value: "{{ ((states(external_measured_room_sensor) | float(-80)) * 100)| round(0)}}"
  target:
    entity_id: !input "climate"
