sensor:
  - platform: metar
    airport_name: Pontoise
    airport_code: LFPT
    monitored_conditions:
      - time
      - temperature
      - wind
      - pressure
      - visibility
      - precipitation
      - sky
